version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  
  # Maintain dependencies for Composer.
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
    versioning-strategy: increase-if-necessary
    rebase-strategy: disabled
